name: Build APK

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4
      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Instalar dependências
        run: npm install
      - name: Criar projeto Android
        run: npm run android:init
      - name: Sincronizar aplicativo
        run: npm run android:sync
      - name: Gerar APK de teste
        run: cd android && ./gradlew assembleDebug --no-daemon
      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: StudioFlow-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
